// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    index: function(req, res) {},
    show: function(req, res) {},
    create: function(req, res) {},
    update: function(req, res) {},
    destroy: function(req, res) {}
  };

}).call(this);
